use super::*;

pub struct Database {
    pub(super) conn: Connection,
    pub(super) path: String,
    /// Process-local active-time authority for unfinalized policy-4 sessions. These entries are
    /// intentionally not durable: after a restart an unfinalized renderer counter cannot mint proof,
    /// while an already-durable exact receipt remains replayable from SQLite.
    pub(super) playback_live_sessions: Mutex<HashMap<String, u64>>,
    /// Only immutable pool identity is cached; few-shot decisions are always read fresh.
    pub(crate) learning_pool_cache: Mutex<Option<crate::review_pool::LearningPoolCache>>,
    #[cfg(test)]
    pub(super) playback_test_clock: Mutex<Option<(i64, u64)>>,
}

impl Database {
    #[cfg(not(test))]
    pub(super) fn from_connection(conn: Connection, path: String) -> Self {
        Self { conn, path, playback_live_sessions: Mutex::new(HashMap::new()), learning_pool_cache: Mutex::new(None) }
    }

    #[cfg(test)]
    pub(super) fn from_connection(conn: Connection, path: String) -> Self {
        Self {
            conn,
            path,
            playback_live_sessions: Mutex::new(HashMap::new()),
            learning_pool_cache: Mutex::new(None),
            playback_test_clock: Mutex::new(None),
        }
    }
}

pub(super) type SchemaObjectContract = (String, String, String, String);

pub(super) static CURRENT_SCHEMA_CONTRACT: OnceLock<Result<Vec<SchemaObjectContract>, String>> = OnceLock::new();

pub(super) fn normalized_schema_sql(name: &str, sql: Option<String>) -> String {
    // FTS5's shadow-table DDL is generated by the bundled SQLite engine rather than by Cortex. Its
    // spelling can change across SQLite patch releases while its required names/relationships stay
    // stable, so bind those internal objects by name/type/table and bind every Cortex-authored object
    // by normalized SQL as well.
    if name.starts_with("segments_fts_") {
        return "<sqlite-fts5-shadow>".to_string();
    }
    sql.unwrap_or_default()
        .trim()
        .trim_end_matches(';')
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .to_ascii_lowercase()
}

pub(super) fn read_schema_contract(conn: &Connection) -> AppResult<Vec<SchemaObjectContract>> {
    let mut statement = conn.prepare(
        "SELECT type, name, tbl_name, sql
           FROM sqlite_schema
          WHERE name NOT LIKE 'sqlite_%'
          ORDER BY type, name",
    )?;
    let rows = statement
        .query_map([], |row| {
            let kind: String = row.get(0)?;
            let name: String = row.get(1)?;
            let table: String = row.get(2)?;
            let sql: Option<String> = row.get(3)?;
            Ok((kind, name.clone(), table, normalized_schema_sql(&name, sql)))
        })?
        .collect::<Result<Vec<_>, _>>()?;
    Ok(rows)
}

pub(super) fn expected_schema_contract() -> AppResult<&'static Vec<SchemaObjectContract>> {
    CURRENT_SCHEMA_CONTRACT
        .get_or_init(|| -> Result<Vec<SchemaObjectContract>, String> {
            let reference = Database::open(":memory:").map_err(|error| error.to_string())?;
            reference.initialize_inner(false).map_err(|error| error.to_string())?;
            read_schema_contract(reference.connection()).map_err(|error| error.to_string())
        })
        .as_ref()
        .map_err(|error| AppError::Other(format!("cannot construct current schema contract: {error}")))
}

pub(crate) fn validate_current_schema_contract(conn: &Connection) -> AppResult<()> {
    let expected = expected_schema_contract()?;
    validate_schema_contract_against(conn, expected)
}

/// Every finalized policy-4 receipt, and every desktop decision that consumed one, must retain exact
/// immutable authority. Schema/FK checks prove object shape and target existence; this semantic pass
/// additionally re-derives interval coverage/hash and the decision operation digest. It runs at
/// startup and on staged restores, so a trigger-disabled or externally edited database fails closed.
pub(super) fn validate_policy4_effect_authority(conn: &Connection) -> AppResult<()> {
    let schema_version: i64 =
        conn.query_row("SELECT COALESCE(MAX(version), 0) FROM schema_migrations", [], |row| row.get(0))?;
    if schema_version < 67 {
        return Ok(());
    }

    let operation_namespace_collisions: i64 = conn.query_row(
        "WITH canonical_operations(operation_id) AS (
             SELECT operation_id FROM review_events WHERE operation_id IS NOT NULL
             UNION SELECT operation_id FROM human_decision_effect_events WHERE operation_id IS NOT NULL
             UNION SELECT operation_id FROM human_decision_effect_reversals
             UNION SELECT operation_id FROM review_flag_effect_events
             UNION SELECT operation_id FROM review_flag_effect_reversals
         ),
         independent_operations(operation_id) AS (
             SELECT operation_id FROM independent_review_decisions
             UNION ALL
             SELECT operation_id FROM independent_review_reversals
             UNION ALL
             SELECT operation_id FROM review_pool_decisions
             UNION ALL
             SELECT operation_id FROM review_pool_reversals
         )
         SELECT
             (SELECT COUNT(*) FROM independent_operations independent
               WHERE EXISTS (
                   SELECT 1 FROM canonical_operations canonical
                    WHERE canonical.operation_id=independent.operation_id
               ))
           + (SELECT COUNT(*) FROM (
                 SELECT operation_id FROM independent_operations
                  GROUP BY operation_id HAVING COUNT(*)>1
             ))",
        [],
        |row| row.get(0),
    )?;
    if operation_namespace_collisions != 0 {
        return Err(AppError::Other(format!(
            "E_REVIEW_OPERATION_NAMESPACE_COLLISION: database contains {operation_namespace_collisions} operation UUID(s) bound to both canonical and independent review truth"
        )));
    }

    // A reviewer may listen and finalize a receipt, then close the app before deciding. Those
    // unconsumed receipts are still immutable evidence and must receive the same startup/restore
    // semantic validation as effect-bound receipts; otherwise a shaped but forged interval digest
    // can sit undetected until a later decision consumes it.
    let finalized_receipts = {
        let mut statement = conn.prepare(
            "SELECT id, segment_id, segment_revision, authority_session_id
               FROM playback_receipts
              WHERE policy_version=?1
              ORDER BY id",
        )?;
        let rows = statement
            .query_map([DESKTOP_PLAYBACK_POLICY_VERSION], |row| {
                Ok((
                    row.get::<_, i64>(0)?,
                    row.get::<_, String>(1)?,
                    row.get::<_, i64>(2)?,
                    row.get::<_, Option<String>>(3)?,
                ))
            })?
            .collect::<Result<Vec<_>, _>>()?;
        rows
    };
    let mut validated_policy4_authorities = HashSet::with_capacity(finalized_receipts.len());
    for (receipt_id, segment_id, revision, authority_id) in finalized_receipts {
        let Some(authority_id) = authority_id else {
            return Err(AppError::Other(format!(
                "policy-4 playback receipt {receipt_id} has no exact authority session"
            )));
        };
        if !has_sufficient_historical_desktop_playback_authority_v4_on(conn, &segment_id, revision, &authority_id)? {
            return Err(AppError::Other(format!(
                "policy-4 playback receipt {receipt_id} does not match its exact interval authority"
            )));
        }
        validated_policy4_authorities.insert(authority_id);
    }

    let malformed: i64 = conn.query_row(
        "SELECT COUNT(*)
           FROM human_decision_effect_events effect
          WHERE (effect.desktop_review_contract_version IS NOT NULL
                  OR effect.playback_authority_session_id IS NOT NULL)
            AND NOT (
                 (effect.desktop_review_contract_version=1
                  AND effect.playback_authority_session_id IS NOT NULL
                  AND effect.source='desktop'
                  AND effect.reviewer IS NULL
                  AND effect.operation_id IS NOT NULL
                  AND effect.operation_payload_hash IS NOT NULL)
                 OR
                 (effect.desktop_review_contract_version IS NULL
                  AND effect.playback_authority_session_id IS NOT NULL
                  AND effect.source='couch'
                  AND effect.reviewer IS NOT NULL
                  AND effect.review_event_id IS NOT NULL
                  AND EXISTS (
                      SELECT 1 FROM desktop_playback_sessions_v4 session
                       WHERE session.playback_receipt_id=effect.playback_authority_session_id
                         AND session.surface='couch'
                         AND session.reviewer=effect.reviewer COLLATE NOCASE
                         AND session.segment_id=effect.segment_id
                         AND session.segment_revision=effect.prior_revision
                  ))
            )",
        [],
        |row| row.get(0),
    )?;
    if malformed != 0 {
        return Err(AppError::Other(format!("policy-4 decision ledger has {malformed} malformed authority row(s)")));
    }

    let malformed_consumptions: i64 = conn.query_row(
        "SELECT COUNT(*)
           FROM playback_authority_consumptions_v4 consumption
           LEFT JOIN desktop_playback_sessions_v4 session
             ON session.playback_receipt_id=consumption.playback_receipt_id
            AND session.surface='couch'
           LEFT JOIN playback_receipts receipt
             ON receipt.authority_session_id=session.playback_receipt_id
            AND receipt.policy_version=4
          WHERE session.playback_receipt_id IS NULL
             OR receipt.id IS NULL
             OR session.reviewer<>consumption.reviewer COLLATE NOCASE
             OR session.segment_id<>consumption.segment_id
             OR NOT (
                 (consumption.namespace='canonical' AND EXISTS (
                    SELECT 1 FROM human_decision_effect_events effect
                     WHERE effect.playback_authority_session_id=consumption.playback_receipt_id
                       AND effect.segment_id=consumption.segment_id
                       AND effect.reviewer=consumption.reviewer COLLATE NOCASE
                 ))
                 OR (consumption.namespace='spot_check' AND EXISTS (
                    SELECT 1 FROM review_events event
                     WHERE event.operation_id=consumption.operation_id
                       AND event.segment_id=consumption.segment_id
                       AND event.reviewer=consumption.reviewer COLLATE NOCASE
                       AND event.source='couch_spot_check'
                 ))
                 OR (consumption.namespace='independent' AND (
                    EXISTS (
                        SELECT 1 FROM independent_review_decisions decision
                         WHERE decision.operation_id=consumption.operation_id
                           AND decision.segment_id=consumption.segment_id
                           AND decision.reviewer=consumption.reviewer COLLATE NOCASE
                    )
                    OR EXISTS (
                        SELECT 1 FROM review_pool_decisions decision
                         WHERE decision.operation_id=consumption.operation_id
                           AND decision.segment_id=consumption.segment_id
                           AND decision.reviewer=consumption.reviewer COLLATE NOCASE
                           AND decision.action<>'skip'
                           AND decision.served_revision=session.segment_revision
                           AND decision.audio_content_hash=session.audio_content_hash
                    )
                 ))
             )",
        [],
        |row| row.get(0),
    )?;
    if malformed_consumptions != 0 {
        return Err(AppError::Other(format!(
            "policy-4 Couch playback ledger has {malformed_consumptions} orphaned or mismatched consumption row(s)"
        )));
    }

    let mut statement = conn.prepare(
        "SELECT effect.id, effect.segment_id, effect.prior_revision, effect.requested_action,
                effect.requested_transcript, effect.operation_payload_hash,
                effect.playback_authority_session_id,
                session.audio_content_hash, session.source_start_ms, session.source_end_ms,
                receipt.authority_session_id
           FROM human_decision_effect_events effect
           LEFT JOIN desktop_playback_sessions_v4 session
             ON session.playback_receipt_id=effect.playback_authority_session_id
           LEFT JOIN playback_receipts receipt
             ON receipt.authority_session_id=session.playback_receipt_id
            AND receipt.policy_version=4
            AND receipt.segment_id=effect.segment_id
            AND receipt.segment_revision=effect.prior_revision
            AND receipt.audio_fingerprint=session.audio_content_hash
          WHERE effect.desktop_review_contract_version=1",
    )?;
    let rows = statement
        .query_map([], |row| {
            Ok((
                row.get::<_, i64>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, i64>(2)?,
                row.get::<_, String>(3)?,
                row.get::<_, Option<String>>(4)?,
                row.get::<_, String>(5)?,
                row.get::<_, String>(6)?,
                row.get::<_, Option<String>>(7)?,
                row.get::<_, Option<i64>>(8)?,
                row.get::<_, Option<i64>>(9)?,
                row.get::<_, Option<String>>(10)?,
            ))
        })?
        .collect::<Result<Vec<_>, _>>()?;
    drop(statement);

    for (
        effect_id,
        segment_id,
        revision,
        action,
        transcript,
        stored_hash,
        authority_id,
        _content_hash,
        _start,
        _end,
        receipt_authority_id,
    ) in rows
    {
        let (Some(_content_hash), Some(_start), Some(_end), Some(receipt_authority_id)) =
            (_content_hash, _start, _end, receipt_authority_id)
        else {
            return Err(AppError::Other(format!(
                "policy-4 desktop effect {effect_id} has no matching exact playback receipt"
            )));
        };
        if receipt_authority_id != authority_id {
            return Err(AppError::Other(format!(
                "policy-4 desktop effect {effect_id} is joined to the wrong playback receipt"
            )));
        }
        let expected_hash =
            desktop_review_v1_payload_hash(&segment_id, revision, &action, transcript.as_deref(), &authority_id);
        if stored_hash != expected_hash || !validated_policy4_authorities.contains(&authority_id) {
            return Err(AppError::Other(format!(
                "policy-4 desktop effect {effect_id} does not match its exact sufficient receipt"
            )));
        }
    }
    Ok(())
}

/// Validate an exact historical schema prefix without asking that database to satisfy migrations
/// it has not run yet.  The pre-migration safety pin necessarily inspects the old schema before the
/// upgrade; comparing it with HEAD would make every legitimate upgrade fail closed.
pub(crate) fn validate_schema_contract_at_version(conn: &Connection, version: i64) -> AppResult<()> {
    let current = crate::migrations::max_supported_version();
    if version == current {
        return validate_current_schema_contract(conn);
    }
    if version < 1 || version > current {
        return Err(AppError::Other(format!(
            "cannot construct schema contract for unsupported migration v{version} (supported 1..={current})"
        )));
    }

    let reference = Database::open(":memory:")?;
    reference.initialize_inner(false)?;
    let rollback_count = usize::try_from(current - version)
        .map_err(|_| AppError::Other(format!("invalid schema rollback distance from v{current} to v{version}")))?;
    crate::migrations::rollback(&reference, rollback_count)?;
    let expected = read_schema_contract(reference.connection())?;
    validate_schema_contract_against(conn, &expected)
}

pub(super) fn validate_schema_contract_against(conn: &Connection, expected: &[SchemaObjectContract]) -> AppResult<()> {
    let actual = read_schema_contract(conn)?;
    if actual == expected {
        return Ok(());
    }

    let expected_by_name: std::collections::BTreeMap<&str, &SchemaObjectContract> =
        expected.iter().map(|row| (row.1.as_str(), row)).collect();
    let actual_by_name: std::collections::BTreeMap<&str, &SchemaObjectContract> =
        actual.iter().map(|row| (row.1.as_str(), row)).collect();
    let missing: Vec<&str> =
        expected_by_name.keys().filter(|name| !actual_by_name.contains_key(**name)).copied().collect();
    let unknown: Vec<&str> =
        actual_by_name.keys().filter(|name| !expected_by_name.contains_key(**name)).copied().collect();
    let changed: Vec<&str> = expected_by_name
        .iter()
        .filter_map(|(name, expected_row)| {
            actual_by_name.get(name).filter(|actual_row| *actual_row != expected_row).map(|_| *name)
        })
        .collect();
    Err(AppError::Other(format!(
        "database schema does not match this release: missing={missing:?}, unknown={unknown:?}, changed={changed:?}"
    )))
}

pub(super) fn human_verdict_for_decision(decision: &str) -> AppResult<&'static str> {
    match decision {
        "accept" => Ok("human_accept"),
        "edit" => Ok("human_edit"),
        "reject" => Ok("human_reject"),
        other => Err(AppError::Validation(format!("Unknown human decision: {other}"))),
    }
}

/// Canonicalize stored text to Unicode NFC. Sorani/Arabic combining marks (diacritics,
/// madda, hamza) can arrive decomposed from ASR or import; storing inconsistent forms
/// silently fragments FTS search, content-dedup, and WER references that all assume one
/// canonical spelling. Idempotent — NFC of already-NFC text is unchanged.
/// `pub(crate)` so sibling modules can canonicalize the SAME way before comparing against a stored
/// transcript. `couch.rs` needs it to tell a network retry apart from a genuine re-review: the write
/// path NFC-normalizes, so a decomposed (NFD) paste from a phone IME would otherwise never compare
/// equal to the value it just stored, and every retry would look like a brand-new decision.
/// Bump when the sufficiency RULE changes. Stored on every receipt so a row always says which rule
/// it satisfied, instead of being re-judged later under one it never met.
pub const PLAYBACK_POLICY_VERSION: i64 = 3;
/// Desktop policy 4 replaces the renderer-minted cumulative counter with a server-issued media
/// session and an exact, canonical interval union.  Policy 3 remains the deployed Couch contract;
/// desktop review authorization is required to use this stricter policy.
pub const DESKTOP_PLAYBACK_POLICY_VERSION: i64 = 4;
pub(super) const DESKTOP_PLAYBACK_SESSION_TTL_MS: i64 = 30 * 60 * 1_000;
pub(super) const MAX_LIVE_DESKTOP_PLAYBACK_SESSIONS: i64 = 64;
pub(super) const MAX_LIVE_DESKTOP_PLAYBACK_SESSIONS_PER_SEGMENT: i64 = 2;
pub(super) const DESKTOP_PLAYBACK_MAX_RATE: i64 = 2;
pub(super) const MAX_DESKTOP_PLAYBACK_INTERVALS: usize = 4_096;

/// Canonical decoded-PCM identity written by the v51 backfill/import path.
///
/// `audio_fingerprint` (v50) is only a 64-bit spectral candidate bucket and can collide. Playback
/// authorization therefore uses the 64-character BLAKE3 `audio_content_hash` exclusively. The
/// receipt table keeps its legacy column name for schema compatibility, but policy 2+ stores this
/// content hash in that column. Policy 3 additionally binds the exact source span.
pub(crate) fn is_canonical_audio_content_hash(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// How much of the clip's media time must actually have been played.
///
/// Not 100%: a reviewer who has heard the sentence often stops before the trailing silence, and
/// demanding the last frame would train them to leave it running rather than to listen. Not 50%
/// either — half a Sorani sentence is exactly where a plausible-but-wrong verdict comes from.
///
/// 0.85, set by the owner 2026-08-19 against the first real device evidence. The bar opened at 0.90
/// and the observe-mode pilot measured 12 receipts from a live phone:
///
///   1.000 ×6 (replays, capped)   0.974   0.968   0.915   0.907   0.856   0.352
///
/// Two would have been refused at 0.90 and two more sat within 0.015 of it — roughly one honest
/// decision in six rejected, on a flat ratio that punishes short clips hardest (the 0.856 case was a
/// 3.4 s clip missing its last 489 ms of trailing silence). 0.85 keeps the 0.352 refusal, which is
/// the case the guard exists for, and stops rejecting reviewers who heard the whole sentence.
///
/// Twelve samples from ONE device is a thin basis for a calibrated number. Revisit once the pilot
/// has 20+ decisions across both reviewers; a length-aware rule (ratio OR a fixed unheard-tail
/// allowance) is the likelier long-run answer than any single ratio.
pub(super) const MIN_PLAYBACK_COVERAGE_NUMERATOR: i64 = 85;
pub(super) const MIN_PLAYBACK_COVERAGE_DENOMINATOR: i64 = 100;
pub const MIN_PLAYBACK_COVERAGE: f64 = 0.85;
pub const MAX_SOURCE_SPAN_DURATION_DELTA_MS: i64 = 1;

/// A reviewer's record of having heard one clip at one revision.
#[derive(Debug, Clone)]
pub struct PlaybackReceipt {
    pub segment_id: String,
    pub segment_revision: i64,
    pub audio_content_hash: String,
    pub reviewer: Option<String>,
    pub session_id: Option<String>,
    pub started_at_ms: i64,
    pub played_ms: i64,
    pub clip_duration_ms: i64,
    /// Server-resolved source window. Request surfaces leave these `None`; the raw writer accepts
    /// only a canonical pair and policy-3 storage persists both.
    pub source_start_ms: Option<i64>,
    pub source_end_ms: Option<i64>,
}

/// Untrusted playback timing reported by a client. Review revision, audio identity, canonical source
/// span and coverage denominator are deliberately absent; only the database may resolve them.
#[derive(Debug, Clone)]
#[cfg(test)]
pub(crate) struct PlaybackReceiptObservation {
    pub(crate) segment_id: String,
    pub(crate) reviewer: Option<String>,
    pub(crate) session_id: Option<String>,
    pub(crate) started_at_ms: i64,
    pub(crate) played_ms: i64,
    pub(crate) claimed_clip_duration_ms: i64,
}

/// One clip-relative interval the media element traversed continuously.  It uses inclusive start and
/// exclusive end coordinates, in whole milliseconds, and arrives only at the policy-4 finalization
/// boundary.  The database revalidates ordering, bounds, overlap, wall-clock plausibility and sum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DesktopPlaybackInterval {
    pub start_ms: i64,
    pub end_ms: i64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DesktopPlaybackSession {
    pub playback_receipt_id: String,
    pub segment_id: String,
    pub segment_revision: i64,
    pub clip_duration_ms: i64,
    pub expires_at_ms: i64,
}

#[derive(Debug)]
pub(crate) struct TechnicalUnusableSourceSnapshot {
    pub(crate) segment: SpeechSegment,
    pub(crate) review_revision: i64,
    pub(crate) source_path_sha256: String,
    pub(crate) audio_content_hash: Option<String>,
}

pub(super) struct DesktopPlaybackSegmentSnapshot {
    pub(super) audio_path: String,
    pub(super) review_revision: i64,
    pub(super) audio_content_hash: Option<String>,
    pub(super) duration_ms: i64,
    pub(super) alignment_json: Option<String>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct DesktopPlaybackReceipt {
    pub playback_receipt_id: String,
    pub segment_id: String,
    pub segment_revision: i64,
    pub unique_played_ms: i64,
    pub clip_duration_ms: i64,
    pub coverage_ratio: f64,
}

/// Exact server-owned coordinates of one unfinalized Couch media attempt. The HTTP layer keeps this
/// object only in authenticated process memory; the database accepts it at finalization after the
/// server monotonic-time and canonical interval checks have passed, then re-resolves every mutable
/// source coordinate in the same transaction that publishes policy-4 authority.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct CouchPlaybackAttemptAuthority {
    pub(crate) playback_receipt_id: String,
    pub(crate) media_grant_id: String,
    pub(crate) client_attempt_id: String,
    pub(crate) session_binding_sha256: String,
    pub(crate) reviewer: String,
    pub(crate) segment_id: String,
    pub(crate) segment_revision: i64,
    pub(crate) audio_content_hash: String,
    pub(crate) source_path: PathBuf,
    pub(crate) clip_duration_ms: i64,
    pub(crate) source_start_ms: i64,
    pub(crate) source_end_ms: i64,
    pub(crate) issued_at_ms: i64,
    pub(crate) expires_at_ms: i64,
}

/// Server-owned playback identity that must still be valid at the instant a paid review write
/// commits. The HTTP layer checks once for a useful error before entering the write path; this
/// second copy is deliberately carried into the SQLite transaction so a concurrent audio/revision
/// change cannot turn evidence for clip A into a verdict or payment for clip B.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct PlaybackDecisionProof {
    pub(crate) segment_revision: i64,
    pub(crate) audio_content_hash: String,
    pub(crate) source_start_ms: i64,
    pub(crate) source_end_ms: i64,
    /// Present only for desktop policy-4 evidence.  The final decision transaction rechecks this
    /// exact receipt rather than accepting another receipt that happens to match the same clip.
    pub(crate) authority_session_id: Option<String>,
    /// Immutable imported-source bytes held from proof resolution through the SQLite commit. Policy-3
    /// phone evidence has no desktop source lease; policy-4 always carries one.
    pub(crate) source_lease: Option<crate::media::VerifiedMediaSourceLease>,
}

pub(crate) fn canonical_source_span(alignment_json: Option<&str>) -> Option<(i64, i64)> {
    let value = serde_json::from_str::<serde_json::Value>(alignment_json?).ok()?;
    let start = value.get("source_start_ms")?.as_i64()?;
    let end = value.get("source_end_ms")?.as_i64()?;
    (start >= 0 && end > start).then_some((start, end))
}

/// Segment durations come from decoded PCM while alignment endpoints are integer milliseconds;
/// endpoint rounding may differ by one millisecond, but anything larger is a different amount of
/// work and must never authorize playback or compensation.
pub(crate) fn source_span_matches_duration(source_start_ms: i64, source_end_ms: i64, duration_ms: i64) -> bool {
    source_start_ms >= 0
        && source_end_ms > source_start_ms
        && duration_ms > 0
        && (source_end_ms - source_start_ms).abs_diff(duration_ms) <= MAX_SOURCE_SPAN_DURATION_DELTA_MS as u64
}

pub(super) fn validate_playback_receipt_nonnegative_fields(receipt: &PlaybackReceipt) -> AppResult<()> {
    if receipt.segment_revision < 0 {
        return Err(AppError::Validation("cannot record playback evidence with a negative segment revision".into()));
    }
    if receipt.started_at_ms < 0 {
        return Err(AppError::Validation("cannot record playback evidence with a negative start timestamp".into()));
    }
    if receipt.played_ms < 0 {
        return Err(AppError::Validation("cannot record playback evidence with negative played media time".into()));
    }
    Ok(())
}

pub(super) fn playback_server_now_ms() -> AppResult<i64> {
    let millis = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|error| AppError::Other(format!("system clock is before the Unix epoch: {error}")))?
        .as_millis();
    i64::try_from(millis).map_err(|_| AppError::Other("system clock millisecond value overflowed i64".into()))
}

#[cfg(windows)]
#[link(name = "kernel32")]
extern "system" {
    fn QueryUnbiasedInterruptTimePrecise(unbiased_time: *mut u64);
}

/// Active workstation time in Windows 100-nanosecond units. Unlike wall time and
/// `QueryPerformanceCounter`, QueryUnbiasedInterruptTimePrecise excludes sleep/hibernate, so changing
/// the clock or suspending the workstation cannot manufacture listening budget. Windows 11 is the
/// only supported product platform. The portable fallback exists solely for developer/test builds.
#[cfg(windows)]
pub(super) fn playback_active_now_100ns() -> u64 {
    let mut ticks = 0_u64;
    // SAFETY: Windows 11 guarantees this function and the pointer targets one initialized u64 owned
    // by this stack frame. The API returns no borrowed data and writes exactly one ULONGLONG.
    unsafe { QueryUnbiasedInterruptTimePrecise(&mut ticks) };
    ticks
}

#[cfg(not(windows))]
pub(super) fn playback_active_now_100ns() -> u64 {
    static START: OnceLock<std::time::Instant> = OnceLock::new();
    let elapsed = START.get_or_init(std::time::Instant::now).elapsed().as_nanos() / 100;
    u64::try_from(elapsed).unwrap_or(u64::MAX)
}

pub(super) fn canonical_grant_source_path_sha256(path: &Path) -> AppResult<String> {
    let canonical = std::fs::canonicalize(path).map_err(|error| {
        AppError::Validation(format!("playback media grant source is missing or unreadable: {error}"))
    })?;
    let mut value = canonical.to_string_lossy().replace('\\', "/");
    if cfg!(windows) {
        value.make_ascii_lowercase();
    }
    let mut hash = Sha256::new();
    hash.update(b"cortex-desktop-playback-grant-path-v1\0");
    hash.update((value.len() as u64).to_le_bytes());
    hash.update(value.as_bytes());
    Ok(hash.finalize().iter().map(|byte| format!("{byte:02x}")).collect())
}

/// Stable path identity for a source that may currently be missing or unreadable. Imported paths are
/// canonical while present; the lexical absolute fallback preserves that identity when the very
/// failure being audited prevents `canonicalize` from opening the target.
pub(crate) fn technical_unusable_source_path_sha256(path: &Path) -> AppResult<String> {
    let canonical = std::fs::canonicalize(path).or_else(|_| std::path::absolute(path))?;
    let mut value = canonical.to_string_lossy().replace('\\', "/");
    if cfg!(windows) {
        value.make_ascii_lowercase();
    }
    let mut hash = Sha256::new();
    hash.update(b"cortex-technical-unusable-source-path-v1\0");
    hash.update((value.len() as u64).to_le_bytes());
    hash.update(value.as_bytes());
    Ok(hash.finalize().iter().map(|byte| format!("{byte:02x}")).collect())
}

pub(super) fn validate_desktop_playback_intervals(
    intervals: &[DesktopPlaybackInterval],
    clip_duration_ms: i64,
) -> AppResult<(i64, String)> {
    if intervals.is_empty() {
        return Err(AppError::Validation(
            "E_NO_PLAYBACK_EVIDENCE: a desktop playback session contains no observed media interval".into(),
        ));
    }
    if intervals.len() > MAX_DESKTOP_PLAYBACK_INTERVALS {
        return Err(AppError::Validation(format!(
            "desktop playback evidence exceeds the {MAX_DESKTOP_PLAYBACK_INTERVALS}-interval safety bound"
        )));
    }
    if clip_duration_ms <= 0 {
        return Err(AppError::Validation("desktop playback evidence has no positive server clip duration".into()));
    }

    let mut unique_ms = 0_i64;
    let mut previous_end: Option<i64> = None;
    let mut hash = Sha256::new();
    hash.update(b"cortex-desktop-playback-interval-union-v1\0");
    hash.update((intervals.len() as u64).to_le_bytes());
    for interval in intervals {
        if interval.start_ms < 0 || interval.end_ms <= interval.start_ms || interval.end_ms > clip_duration_ms {
            return Err(AppError::Validation(
                "desktop playback evidence contains an invalid or out-of-bounds interval".into(),
            ));
        }
        if previous_end.is_some_and(|end| interval.start_ms <= end) {
            return Err(AppError::Validation(
                "desktop playback intervals must be sorted, non-overlapping, and non-adjacent".into(),
            ));
        }
        unique_ms = unique_ms
            .checked_add(interval.end_ms - interval.start_ms)
            .ok_or_else(|| AppError::Validation("desktop playback interval sum overflowed".into()))?;
        previous_end = Some(interval.end_ms);
        hash.update(interval.start_ms.to_le_bytes());
        hash.update(interval.end_ms.to_le_bytes());
    }
    if unique_ms > clip_duration_ms {
        return Err(AppError::Validation("desktop playback interval union exceeds the server clip duration".into()));
    }
    Ok((unique_ms, hash.finalize().iter().map(|byte| format!("{byte:02x}")).collect()))
}

pub(crate) const PLAYBACK_EVIDENCE_CHANGED: &str = "E_PLAYBACK_EVIDENCE_CHANGED";
pub(crate) const HIDDEN_ANSWER_KEY_CHANGED: &str = "E_HIDDEN_ANSWER_KEY_CHANGED";

pub(super) fn has_sufficient_playback_evidence_on(
    conn: &Connection,
    segment_id: &str,
    revision: i64,
    content_hash: &str,
    source_start_ms: i64,
    source_end_ms: i64,
    reviewer: Option<&str>,
) -> AppResult<bool> {
    // Reject the proof claim itself before consulting storage. The SQL below independently checks
    // the server row, but an internal caller still cannot present a legacy spectral bucket or an
    // invented identity as an authorization capability.
    if !is_canonical_audio_content_hash(content_hash) || source_start_ms < 0 || source_end_ms <= source_start_ms {
        return Ok(false);
    }
    let sufficient: i64 = conn.query_row(
        "SELECT EXISTS(
            SELECT 1
             FROM playback_receipts p
              JOIN speech_segments s ON s.id = p.segment_id
             WHERE s.id = ?1
               AND COALESCE(s.review_revision, 0) = ?2
               AND typeof(s.audio_content_hash) = 'text'
               AND length(s.audio_content_hash) = 64
               AND s.audio_content_hash NOT GLOB '*[^0-9a-f]*'
               AND s.audio_content_hash = ?3
               AND typeof(p.segment_revision) = 'integer'
               AND p.segment_revision = COALESCE(s.review_revision, 0)
               AND p.audio_fingerprint = s.audio_content_hash
               AND json_valid(s.alignment_json)
               AND json_extract(s.alignment_json, '$.source_start_ms') = ?4
               AND json_extract(s.alignment_json, '$.source_end_ms') = ?5
               AND ABS(
                    (json_extract(s.alignment_json, '$.source_end_ms')
                     - json_extract(s.alignment_json, '$.source_start_ms'))
                    - s.duration_ms
               ) <= ?9
               AND typeof(p.source_start_ms) = 'integer' AND p.source_start_ms = ?4
               AND typeof(p.source_end_ms) = 'integer' AND p.source_end_ms = ?5
               AND p.reviewer IS ?6
               AND typeof(p.policy_version) = 'integer' AND p.policy_version = ?7
               AND typeof(p.started_at_ms) = 'integer' AND p.started_at_ms >= 0
               AND typeof(p.played_ms) = 'integer' AND p.played_ms >= 0
               AND typeof(p.clip_duration_ms) = 'integer' AND p.clip_duration_ms > 0
               AND typeof(s.duration_ms) = 'integer' AND s.duration_ms > 0
               AND p.clip_duration_ms = s.duration_ms
               AND MIN(1.0, CAST(p.played_ms AS REAL) / CAST(p.clip_duration_ms AS REAL)) >= ?8
        )",
        params![
            segment_id,
            revision,
            content_hash,
            source_start_ms,
            source_end_ms,
            reviewer,
            PLAYBACK_POLICY_VERSION,
            MIN_PLAYBACK_COVERAGE,
            MAX_SOURCE_SPAN_DURATION_DELTA_MS,
        ],
        |row| row.get(0),
    )?;
    Ok(sufficient == 1)
}

#[allow(clippy::too_many_arguments)]
pub(super) fn has_sufficient_desktop_playback_evidence_v4_on(
    conn: &Connection,
    segment_id: &str,
    revision: i64,
    content_hash: &str,
    source_start_ms: i64,
    source_end_ms: i64,
    reviewer: Option<&str>,
    playback_receipt_id: &str,
) -> AppResult<bool> {
    if uuid::Uuid::parse_str(playback_receipt_id).is_err()
        || !is_canonical_audio_content_hash(content_hash)
        || source_start_ms < 0
        || source_end_ms <= source_start_ms
    {
        return Ok(false);
    }
    let sufficient: i64 = conn.query_row(
        "SELECT EXISTS(
             SELECT 1 FROM playback_receipts receipt
             JOIN desktop_playback_sessions_v4 session
               ON session.playback_receipt_id=receipt.authority_session_id
             JOIN speech_segments segment ON segment.id=receipt.segment_id
            WHERE receipt.authority_session_id=?1
              AND receipt.policy_version=?2
              AND receipt.segment_id=?3
              AND receipt.segment_revision=?4
              AND receipt.audio_fingerprint=?5
              AND receipt.reviewer IS ?6
              AND receipt.source_start_ms=?7
              AND receipt.source_end_ms=?8
              AND receipt.clip_duration_ms=segment.duration_ms
              AND receipt.played_ms=(
                  SELECT COALESCE(SUM(interval.end_ms-interval.start_ms),0)
                    FROM desktop_playback_intervals_v4 interval
                   WHERE interval.playback_receipt_id=receipt.authority_session_id
              )
              AND MIN(1.0,CAST(receipt.played_ms AS REAL)/CAST(receipt.clip_duration_ms AS REAL))>=?9
              AND session.segment_id=segment.id
              AND session.segment_revision=COALESCE(segment.review_revision,0)
              AND session.audio_content_hash=segment.audio_content_hash
              AND session.source_start_ms=json_extract(segment.alignment_json,'$.source_start_ms')
              AND session.source_end_ms=json_extract(segment.alignment_json,'$.source_end_ms')
         )",
        params![
            playback_receipt_id,
            DESKTOP_PLAYBACK_POLICY_VERSION,
            segment_id,
            revision,
            content_hash,
            reviewer,
            source_start_ms,
            source_end_ms,
            MIN_PLAYBACK_COVERAGE,
        ],
        |row| row.get(0),
    )?;
    Ok(sufficient == 1)
}

/// Consume one finalized Couch receipt exactly once across every judgement namespace. This must be
/// called inside the same SQLite transaction that publishes the corresponding canonical, spot-check,
/// or independent decision. An exact same-operation race is harmless; any different operation,
/// reviewer, segment, or namespace is a hard replay conflict.
pub(crate) fn consume_couch_playback_authority_on(
    conn: &Connection,
    playback_receipt_id: &str,
    namespace: &str,
    operation_id: &str,
    reviewer: &str,
    segment_id: &str,
    created_at_ms: i64,
) -> AppResult<()> {
    if !matches!(namespace, "canonical" | "spot_check" | "independent")
        || uuid::Uuid::parse_str(playback_receipt_id).is_err()
        || uuid::Uuid::parse_str(operation_id).is_err()
        || reviewer.trim().is_empty()
        || segment_id.trim().is_empty()
        || created_at_ms <= 0
    {
        return Err(AppError::Validation("Couch playback consumption identity is invalid".into()));
    }
    type Existing = (String, String, String, String);
    let existing: Option<Existing> = conn
        .query_row(
            "SELECT namespace,operation_id,reviewer,segment_id
               FROM playback_authority_consumptions_v4
              WHERE playback_receipt_id=?1 OR operation_id=?2",
            params![playback_receipt_id, operation_id],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?)),
        )
        .optional()?;
    if let Some((stored_namespace, stored_operation, stored_reviewer, stored_segment)) = existing {
        if stored_namespace == namespace
            && stored_operation == operation_id
            && stored_reviewer.eq_ignore_ascii_case(reviewer)
            && stored_segment == segment_id
        {
            return Ok(());
        }
        return Err(AppError::Validation(
            "E_PLAYBACK_RECEIPT_CONSUMED: policy-4 Couch playback authority was already used by another human operation"
                .into(),
        ));
    }
    conn.execute(
        "INSERT INTO playback_authority_consumptions_v4
            (playback_receipt_id,namespace,operation_id,reviewer,segment_id,created_at_ms)
         VALUES (?1,?2,?3,?4,?5,?6)",
        params![playback_receipt_id, namespace, operation_id, reviewer, segment_id, created_at_ms],
    )?;
    Ok(())
}

/// Owner canon 2026-09-04: a paid pool second opinion proves the same policy-4 listening as a first
/// opinion, inside the transaction that commits and pays it. The live evidence predicate re-checks
/// reviewer, clip, revision, audio identity, span, coverage and interval sum against the current
/// row; the consumption then binds the receipt to exactly this pool operation. The namespace is
/// `independent` (the table's CHECK admits canonical | spot_check | independent): a pool judgement IS
/// an independent second opinion, and the startup/restore audit links the row back through
/// `review_pool_decisions.operation_id`, served revision and audio identity.
#[allow(clippy::too_many_arguments)]
pub(crate) fn consume_couch_playback_authority_for_pool_decision_on(
    conn: &Connection,
    playback_receipt_id: &str,
    reviewer: &str,
    segment_id: &str,
    revision: i64,
    content_hash: &str,
    source_start_ms: i64,
    source_end_ms: i64,
    operation_id: &str,
    created_at_ms: i64,
) -> AppResult<()> {
    let sufficient = has_sufficient_desktop_playback_evidence_v4_on(
        conn,
        segment_id,
        revision,
        content_hash,
        source_start_ms,
        source_end_ms,
        Some(reviewer),
        playback_receipt_id,
    )?;
    if !sufficient {
        return Err(AppError::Validation(
            "E_NO_PLAYBACK_EVIDENCE: a paid pool judgement must be bound to this reviewer's verified policy-4 traversal of exactly this clip revision"
                .into(),
        ));
    }
    consume_couch_playback_authority_on(
        conn,
        playback_receipt_id,
        "independent",
        operation_id,
        reviewer,
        segment_id,
        created_at_ms,
    )
}

/// Re-derive one historical policy-4 authority without consulting the mutable current segment row.
/// A successful decision advances `speech_segments.review_revision`, so the live precommit predicate
/// above is intentionally unsuitable for startup/restore validation. Historical proof instead binds
/// the immutable effect's prior revision to its immutable session, receipt and exact interval union.
pub(super) fn has_sufficient_historical_desktop_playback_authority_v4_on(
    conn: &Connection,
    segment_id: &str,
    revision: i64,
    playback_receipt_id: &str,
) -> AppResult<bool> {
    type HistoricalAuthority = (
        String,
        i64,
        String,
        Option<String>,
        String,
        Option<String>,
        i64,
        i64,
        i64,
        i64,
        String,
        i64,
        String,
        Option<String>,
        Option<String>,
        i64,
        i64,
        i64,
        f64,
        i64,
        i64,
        String,
    );
    let authority: Option<HistoricalAuthority> = conn
        .query_row(
            "SELECT session.segment_id, session.segment_revision, session.audio_content_hash,
                    session.reviewer, session.surface, session.session_binding_sha256,
                    session.clip_duration_ms, session.source_start_ms,
                    session.source_end_ms, session.issued_at_ms,
                    receipt.segment_id, receipt.segment_revision, receipt.audio_fingerprint,
                    receipt.reviewer, receipt.session_id, receipt.started_at_ms, receipt.played_ms,
                    receipt.clip_duration_ms, receipt.coverage_ratio, receipt.source_start_ms,
                    receipt.source_end_ms, receipt.interval_union_sha256
               FROM desktop_playback_sessions_v4 session
               JOIN playback_receipts receipt
                 ON receipt.authority_session_id=session.playback_receipt_id
                AND receipt.policy_version=?2
              WHERE session.playback_receipt_id=?1",
            params![playback_receipt_id, DESKTOP_PLAYBACK_POLICY_VERSION],
            |row| {
                Ok((
                    row.get(0)?,
                    row.get(1)?,
                    row.get(2)?,
                    row.get(3)?,
                    row.get(4)?,
                    row.get(5)?,
                    row.get(6)?,
                    row.get(7)?,
                    row.get(8)?,
                    row.get(9)?,
                    row.get(10)?,
                    row.get(11)?,
                    row.get(12)?,
                    row.get(13)?,
                    row.get(14)?,
                    row.get(15)?,
                    row.get(16)?,
                    row.get(17)?,
                    row.get(18)?,
                    row.get(19)?,
                    row.get(20)?,
                    row.get(21)?,
                ))
            },
        )
        .optional()?;
    let Some((
        session_segment,
        session_revision,
        content_hash,
        session_reviewer,
        surface,
        session_binding_sha256,
        session_duration,
        session_start,
        session_end,
        issued_at_ms,
        receipt_segment,
        receipt_revision,
        receipt_content_hash,
        receipt_reviewer,
        receipt_session_id,
        receipt_started_at_ms,
        receipt_played_ms,
        receipt_duration,
        receipt_coverage,
        receipt_start,
        receipt_end,
        stored_interval_hash,
    )) = authority
    else {
        return Ok(false);
    };
    let session_identity_is_valid = match surface.as_str() {
        "desktop" => session_reviewer.is_none() && receipt_reviewer.is_none() && session_binding_sha256.is_none(),
        "couch" => {
            session_reviewer.as_deref().is_some_and(|reviewer| !reviewer.trim().is_empty() && reviewer.len() <= 100)
                && receipt_reviewer == session_reviewer
                && session_binding_sha256.as_deref().is_some_and(is_canonical_audio_content_hash)
        }
        _ => false,
    };
    if session_segment != segment_id
        || receipt_segment != segment_id
        || session_revision != revision
        || receipt_revision != revision
        || !is_canonical_audio_content_hash(&content_hash)
        || receipt_content_hash != content_hash
        || !session_identity_is_valid
        || receipt_session_id.as_deref() != Some(playback_receipt_id)
        || session_duration != receipt_duration
        || !source_span_matches_duration(session_start, session_end, session_duration)
        || receipt_start != session_start
        || receipt_end != session_end
        || receipt_started_at_ms != issued_at_ms
    {
        return Ok(false);
    }

    let interval_rows = {
        let mut statement = conn.prepare(
            "SELECT ordinal, start_ms, end_ms
               FROM desktop_playback_intervals_v4
              WHERE playback_receipt_id=?1
              ORDER BY ordinal",
        )?;
        let rows = statement
            .query_map([playback_receipt_id], |row| {
                Ok((row.get::<_, i64>(0)?, DesktopPlaybackInterval { start_ms: row.get(1)?, end_ms: row.get(2)? }))
            })?
            .collect::<Result<Vec<_>, _>>()?;
        rows
    };
    if interval_rows
        .iter()
        .enumerate()
        .any(|(index, (ordinal, _))| *ordinal != i64::try_from(index).unwrap_or(i64::MAX))
    {
        return Ok(false);
    }
    let intervals = interval_rows.into_iter().map(|(_, interval)| interval).collect::<Vec<_>>();
    let (derived_played_ms, derived_interval_hash) =
        match validate_desktop_playback_intervals(&intervals, session_duration) {
            Ok(value) => value,
            Err(_) => return Ok(false),
        };
    let required_played_ms = session_duration
        .checked_mul(MIN_PLAYBACK_COVERAGE_NUMERATOR)
        .and_then(|value| value.checked_add(MIN_PLAYBACK_COVERAGE_DENOMINATOR - 1))
        .map(|value| value / MIN_PLAYBACK_COVERAGE_DENOMINATOR);
    let Some(required_played_ms) = required_played_ms else {
        return Ok(false);
    };
    let derived_coverage = derived_played_ms as f64 / session_duration as f64;
    Ok(derived_played_ms == receipt_played_ms
        && derived_played_ms >= required_played_ms
        && derived_interval_hash == stored_interval_hash
        && receipt_coverage.is_finite()
        && (receipt_coverage - derived_coverage).abs() <= 0.000000001)
}

/// Re-read the exact hidden-check answer from the transaction snapshot using the one canonical
/// corpus policy implementation. Repeating that policy as SQL would eventually drift from
/// `quality::human_verified_text` / `is_human_rejected` and grade a reviewer against a key that the
/// exporter no longer considers human gold.
pub(super) fn current_hidden_answer_key_on(conn: &Connection, segment_id: &str) -> AppResult<Option<String>> {
    let segment: Option<SpeechSegment> = conn
        .query_row(
            "SELECT raw_transcript, annotated_transcript, verdict_transcript, human_decision, verdict
               FROM speech_segments
              WHERE id = ?1",
            [segment_id],
            |row| {
                Ok(SpeechSegment {
                    id: segment_id.to_string(),
                    raw_transcript: row.get(0)?,
                    annotated_transcript: row.get(1)?,
                    verdict_transcript: row.get(2)?,
                    human_decision: row.get(3)?,
                    verdict: row.get(4)?,
                    ..Default::default()
                })
            },
        )
        .optional()?;
    let Some(segment) = segment else {
        return Ok(None);
    };
    if crate::quality::is_excluded_from_exports(&segment) {
        return Ok(None);
    }
    Ok(crate::quality::human_verified_text(&segment).map(str::to_string))
}

pub(crate) fn to_nfc(s: &str) -> String {
    s.nfc().collect()
}

/// NFC-canonicalize a segment's three transcript fields for storage.
pub(super) fn nfc_transcripts(seg: &SpeechSegment) -> (String, Option<String>, Option<String>) {
    (
        to_nfc(&seg.raw_transcript),
        seg.normalized_transcript.as_deref().map(to_nfc),
        seg.annotated_transcript.as_deref().map(to_nfc),
    )
}

/// Review-owned fields a pasted dataset is attempting to author.
///
/// Since schema v60, human truth is valid only when it is committed through the atomic decision /
/// flag effect graph (or was frozen by the v60 legacy-authority migration). A renderer-supplied JSON
/// row cannot prove either authority. Keep this list deliberately broader than just the final
/// `human_decision`: verdict evidence and gold/verification flags affect queues, pay, export, or
/// training just as directly and therefore cannot be smuggled in through the machine-data merge.
pub(super) fn imported_review_owned_fields(seg: &SpeechSegment) -> Vec<&'static str> {
    let mut fields = Vec::new();
    if seg.annotated_transcript.is_some() {
        fields.push("annotatedTranscript");
    }
    if seg.verified {
        fields.push("verified");
    }
    if seg.verdict.is_some() {
        fields.push("verdict");
    }
    if seg.verdict_transcript.is_some() {
        fields.push("verdictTranscript");
    }
    if seg.rationale.is_some() {
        fields.push("rationale");
    }
    if seg.evidence_json.is_some() {
        fields.push("evidenceJson");
    }
    if seg.agreement_score.is_some() {
        fields.push("agreementScore");
    }
    if seg.escalated {
        fields.push("escalated");
    }
    if seg.human_decision.is_some() {
        fields.push("humanDecision");
    }
    if seg.corrected_at.is_some() {
        fields.push("correctedAt");
    }
    if seg.is_gold {
        fields.push("isGold");
    }
    if seg.reviewed_by.is_some() {
        fields.push("reviewedBy");
    }
    fields
}

pub(crate) fn review_owned_projection_matches(left: &SpeechSegment, right: &SpeechSegment) -> bool {
    left.annotated_transcript == right.annotated_transcript
        && left.verified == right.verified
        && left.verdict == right.verdict
        && left.verdict_transcript == right.verdict_transcript
        && left.rationale == right.rationale
        && left.evidence_json == right.evidence_json
        && left.agreement_score == right.agreement_score
        && left.escalated == right.escalated
        && left.human_decision == right.human_decision
        && left.corrected_at == right.corrected_at
        && left.is_gold == right.is_gold
        && left.reviewed_by == right.reviewed_by
}

pub(super) fn history_source_identity_matches(left: &SpeechSegment, right: &SpeechSegment) -> bool {
    left.id == right.id
        && left.audio_path == right.audio_path
        && left.alignment_json == right.alignment_json
        && left.duration_ms == right.duration_ms
}

pub(super) fn history_machine_projection_matches(left: &SpeechSegment, right: &SpeechSegment) -> bool {
    left.raw_transcript == right.raw_transcript
        && left.normalized_transcript == right.normalized_transcript
        && left.speaker_id == right.speaker_id
        && left.confidence == right.confidence
        && left.ctc_score == right.ctc_score
        && left.clipping_ratio == right.clipping_ratio
        && left.rms_db == right.rms_db
        && left.snr_db == right.snr_db
        && left.split == right.split
        && left.signal_anomaly_score == right.signal_anomaly_score
        && left.alignment_quality == right.alignment_quality
        && left.model_version_id.as_deref().unwrap_or("unknown@pre-registry")
            == right.model_version_id.as_deref().unwrap_or("unknown@pre-registry")
        && left.confidence_source.as_deref().unwrap_or("unknown")
            == right.confidence_source.as_deref().unwrap_or("unknown")
        && left.cloud_call == right.cloud_call
        && left.decoder_config_hash == right.decoder_config_hash
        && left.normalizer_version == right.normalizer_version
        && left.denoised == right.denoised
        && left.diarized == right.diarized
        && left.vad_backend == right.vad_backend
        && left.speaker_change_score == right.speaker_change_score
}

/// Fold Sorani codepoint variants (Kaf ك/ک, Yeh ي/ی, Heh, Hamza, ZWNJ, tatweel) in a
/// full-text search query so it matches the canonical `normalized_transcript` column
/// regardless of which keyboard variant the user typed — the FTS index stores the
/// normalizer's unified form, but a raw query in a different codepoint would never
/// match it. Digit conversion/verbalization is intentionally skipped so a digit query
/// still matches the raw transcript; the letter rules mirror those applied to the
/// stored normalized text.
pub(super) fn normalize_search_query(text: &str) -> String {
    crate::normalizer::SoraniNormalizer::with_config(crate::normalizer::NormalizationConfig {
        normalize_numbers: false,
        verbalize_numbers: false,
        normalize_hamza: true,
        remove_diacritics: false,
    })
    .normalize(text)
}

/// Convert free-text search input into a SAFE FTS5 `MATCH` string. FTS5 parses the bound value as a
/// full-text *query*, so bare metacharacters (`"` `:` `*` `(` `)` `^` `-` and the bareword keywords
/// `AND`/`OR`/`NEAR`) make it raise a hard error on ordinary punctuation — e.g. a user typing a
/// single `"` or `:` in the transcript search box would get a low-level "fts5: syntax error" instead
/// of results. We treat the box as literal text: split on whitespace and wrap each token as a quoted
/// FTS5 string (internal `"` doubled), which FTS5 reads as a literal term. Tokens are implicitly
/// AND-ed (matching the previous behaviour for multi-word queries). Returns `""` for whitespace-only
/// input so the caller can short-circuit to an empty result.
/// A token a person read off a file listing: ASCII, at least one digit, and a `_`, `-` or `.`.
/// `lamo_016604`, `KBHP-EP08.wav` — never a plain word such as a folder name (Round-23 #7).
pub fn looks_like_file_token(token: &str) -> bool {
    token.len() >= 4
        && token.is_ascii()
        && token.chars().any(|c| c.is_ascii_digit())
        && token.chars().any(|c| matches!(c, '_' | '-' | '.'))
        && token.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.'))
}

pub(super) fn to_fts5_match(query: &str) -> String {
    // Control characters (NUL and other C0/C1) are never meaningful search terms and an embedded
    // NUL makes SQLite/FTS5 raise a hard error (interior NUL in a bound string), so map every
    // control char to a separator before tokenizing — they can't survive into the MATCH string.
    let cleaned: String = query.chars().map(|c| if c.is_control() { ' ' } else { c }).collect();
    cleaned
        .split_whitespace()
        .filter(|t| !t.is_empty())
        .map(|t| format!("\"{}\"", t.replace('"', "\"\"")))
        .collect::<Vec<_>>()
        .join(" ")
}

/// The only split labels the export/stats math understands.
pub(super) const VALID_SPLITS: &[&str] = &["train", "validation", "test"];

/// Longest gap still counted as "one reviewing session" for per-reviewer throughput (Migration v45).
/// Matches `stats.rs::SESSION_GAP_MS` deliberately, so the phone figure and the desktop figure mean
/// the same thing; a reviewer who closes the page and returns tomorrow did not spend fourteen hours
/// on one clip.
pub(super) const REVIEW_SESSION_GAP_MS: i64 = 300_000; // 5 minutes

/// SQL mirror of [`crate::quality::is_placeholder_transcript`] (plus empty) for one transcript column
/// expression — the ONE definition every SQL site must use.
///
/// The couch queue used to narrow on `[%]` alone while the Rust authority also calls a trimmed,
/// case-insensitive `n/a` / `null` a placeholder. An `n/a` draft therefore passed the queue filter and
/// was served to a PAID reviewer, who could blind-accept it into a verified gold row without the
/// champion ever having drafted the clip. Generated from one place so the two cannot drift again;
/// `LOWER`/`LIKE` here are ASCII-folding, matching `eq_ignore_ascii_case` on the Rust side.
pub(crate) fn placeholder_or_empty_transcript_sql(column: &str) -> String {
    format!(
        "(TRIM(COALESCE({column}, '')) = '' \
         OR TRIM(COALESCE({column}, '')) LIKE '[%]' \
         OR LOWER(TRIM(COALESCE({column}, ''))) IN ('n/a', 'null'))"
    )
}

/// Refuse to persist a blank ASR draft over an existing one.
///
/// The blank-transcript-overwrite class has been fixed twice at the CALL SITE (batch_transcribe's
/// match-guard, the WSL refine loop's skip) and came back both times, because an engine that returns
/// `Ok("")` on a quiet clip looks like success to every new caller. The guard belongs at the shared
/// persist boundary: the `verified = 0` fence protects human rows, not a good unreviewed champion
/// draft. An error, not `Ok(false)` — a blank result is an ASR failure, and canon says a per-clip
/// failure is a HARD STOP, never something that reads as a review race.
pub(super) fn refuse_blank_asr_persist(segment_id: &str, raw_transcript: &str) -> AppResult<()> {
    if raw_transcript.trim().is_empty() {
        return Err(AppError::Validation(format!(
            "refusing to persist a blank ASR transcript for segment {segment_id}: an empty draft is a failed transcription, not a result"
        )));
    }
    Ok(())
}

/// Generous stored-hypothesis limits derived from the 2026-08-28 owner snapshot (maximum four
/// hypotheses, 638 transcript bytes, and 1,711 aggregate transcript bytes per segment). These are
/// fail-closed corruption/resource boundaries, not product-quality limits; they intentionally leave
/// several orders of magnitude of headroom and never truncate evidence.
pub(crate) const MAX_STORED_HYPOTHESES_PER_SEGMENT: usize = 64;
pub(crate) const MAX_STORED_HYPOTHESIS_TRANSCRIPT_BYTES: usize = 512 * 1024;
pub(crate) const MAX_STORED_HYPOTHESIS_TRANSCRIPT_BYTES_PER_SEGMENT: usize = 2 * 1024 * 1024;
pub(crate) const MAX_STORED_HYPOTHESIS_METADATA_FIELD_BYTES: usize = 4 * 1024;
pub(crate) const MAX_STORED_HYPOTHESIS_METADATA_BYTES_PER_SEGMENT: usize = 512 * 1024;

pub(super) fn validate_stored_hypothesis_payload(segment_id: &str, model_id: &str, transcript: &str) -> AppResult<()> {
    crate::validation::input::validate_identifier(segment_id).map_err(AppError::Validation)?;
    crate::validation::input::validate_identifier(model_id).map_err(AppError::Validation)?;
    if transcript.len() > MAX_STORED_HYPOTHESIS_TRANSCRIPT_BYTES {
        return Err(AppError::Validation(format!(
            "E_HYPOTHESIS_LIMIT_EXCEEDED: hypothesis transcript is {} bytes; maximum is {}",
            transcript.len(),
            MAX_STORED_HYPOTHESIS_TRANSCRIPT_BYTES
        )));
    }
    Ok(())
}

pub(super) fn validate_stored_hypothesis_upsert_on(
    conn: &Connection,
    segment_id: &str,
    model_id: &str,
    transcript: &str,
) -> AppResult<()> {
    validate_stored_hypothesis_payload(segment_id, model_id, transcript)?;
    let (other_count, other_transcript_bytes, other_metadata_bytes): (i64, i64, i64) = conn.query_row(
        "SELECT count(*),
                COALESCE(sum(length(CAST(transcript AS BLOB))),0),
                COALESCE(sum(length(CAST(COALESCE(model_id,'') AS BLOB))
                           +length(CAST(COALESCE(model_version_id,'') AS BLOB))
                           +length(CAST(COALESCE(created_at,'') AS BLOB))),0)
           FROM segment_hypotheses
          WHERE segment_id=?1 AND model_id<>?2",
        params![segment_id, model_id],
        |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
    )?;
    let projected_count = usize::try_from(other_count)
        .ok()
        .and_then(|count| count.checked_add(1))
        .ok_or_else(|| AppError::Validation("E_HYPOTHESIS_LIMIT_EXCEEDED: invalid hypothesis count".into()))?;
    let projected_transcript_bytes =
        usize::try_from(other_transcript_bytes).ok().and_then(|bytes| bytes.checked_add(transcript.len())).ok_or_else(
            || AppError::Validation("E_HYPOTHESIS_LIMIT_EXCEEDED: invalid aggregate hypothesis bytes".into()),
        )?;
    // An UPSERT retains an existing model_version_id, while a fresh insert receives the schema
    // default. Reserve the full allowed metadata-field budget plus a timestamp allowance; this is
    // conservative even for a legacy same-model row without loading its TEXT into Rust.
    let new_metadata_bytes = model_id
        .len()
        .checked_add(MAX_STORED_HYPOTHESIS_METADATA_FIELD_BYTES)
        .and_then(|bytes| bytes.checked_add(64))
        .ok_or_else(|| AppError::Validation("E_HYPOTHESIS_LIMIT_EXCEEDED: invalid hypothesis metadata bytes".into()))?;
    let projected_metadata_bytes = usize::try_from(other_metadata_bytes)
        .ok()
        .and_then(|bytes| bytes.checked_add(new_metadata_bytes))
        .ok_or_else(|| AppError::Validation("E_HYPOTHESIS_LIMIT_EXCEEDED: invalid aggregate metadata bytes".into()))?;
    if projected_count > MAX_STORED_HYPOTHESES_PER_SEGMENT
        || projected_transcript_bytes > MAX_STORED_HYPOTHESIS_TRANSCRIPT_BYTES_PER_SEGMENT
        || projected_metadata_bytes > MAX_STORED_HYPOTHESIS_METADATA_BYTES_PER_SEGMENT
    {
        return Err(AppError::Validation(format!(
            "E_HYPOTHESIS_LIMIT_EXCEEDED: projected hypothesis authority is {projected_count} rows, \
             {projected_transcript_bytes} transcript bytes, and {projected_metadata_bytes} metadata bytes"
        )));
    }
    Ok(())
}

pub(super) const SEGMENT_SELECT_COLUMNS: &str = "id, created_at, audio_path, raw_transcript, normalized_transcript,
                    annotated_transcript, alignment_json, duration_ms, speaker_id, verified,
                    confidence, ctc_score, clipping_ratio, rms_db, snr_db, split, signal_anomaly_score,
                    verdict, verdict_transcript, rationale, evidence_json,
                    agreement_score, escalated, human_decision, corrected_at, is_gold,
                    alignment_quality, model_version_id, confidence_source, cloud_call,
                    decoder_config_hash, normalizer_version, denoised, diarized, vad_backend,
                    reviewed_by, speaker_change_score";

// List rows preserve the SpeechSegment wire shape but omit large payloads that are hydrated only
// when a row is selected.
pub(super) const SEGMENT_LIST_SELECT_COLUMNS: &str =
    "id, created_at, audio_path, raw_transcript, normalized_transcript,
                    annotated_transcript, NULL AS alignment_json, duration_ms, speaker_id, verified,
                    confidence, ctc_score, clipping_ratio, rms_db, snr_db, split, signal_anomaly_score,
                    verdict, verdict_transcript, rationale, NULL AS evidence_json,
                    agreement_score, escalated, human_decision, corrected_at, is_gold,
                    alignment_quality, model_version_id, confidence_source, cloud_call,
                    decoder_config_hash, normalizer_version, denoised, diarized, vad_backend,
                    reviewed_by, speaker_change_score";

pub(super) fn canonical_segment_sort(sort: &str) -> &str {
    match sort {
        "active_learning" => "activeLearning",
        "suspect_first" => "suspectFirst",
        "oldest" | "duration" | "verified" | "confidence" | "activeLearning" | "suspectFirst" => sort,
        _ => "newest",
    }
}

pub(super) fn segment_page_scope(
    verified: Option<bool>,
    text_query: Option<&str>,
    focus: Option<&std::collections::HashSet<String>>,
) -> String {
    let mut hash = Sha256::new();
    hash.update(match verified {
        Some(true) => b"verified:1".as_slice(),
        Some(false) => b"verified:0".as_slice(),
        None => b"verified:*".as_slice(),
    });
    hash.update(b"\0query:");
    hash.update(text_query.unwrap_or_default().trim().as_bytes());
    // The focus SET is part of the scope, not just its presence: `total` and every page boundary were
    // computed under one allow-list, and a cursor carried across an edit to voice_focus.json would
    // keep serving pages (and a total) from the retired list.
    hash.update(b"\0focus:");
    if let Some(set) = focus {
        let mut ids: Vec<&str> = set.iter().map(String::as_str).collect();
        ids.sort_unstable();
        for id in ids {
            hash.update(id.as_bytes());
            hash.update(b"\n");
        }
    }
    base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(hash.finalize())
}

pub(super) fn decode_segment_cursor(raw: &str) -> AppResult<SegmentPageCursor> {
    let bytes = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(raw)
        .map_err(|_| AppError::Validation("Invalid segment page cursor".into()))?;
    let cursor: SegmentPageCursor =
        serde_json::from_slice(&bytes).map_err(|_| AppError::Validation("Invalid segment page cursor".into()))?;
    if cursor.version != 1 || cursor.anchor_rowid < 0 || cursor.last.id.is_empty() {
        return Err(AppError::Validation("Unsupported segment page cursor".into()));
    }
    Ok(cursor)
}

pub(super) fn encode_segment_cursor(cursor: &SegmentPageCursor) -> AppResult<String> {
    let bytes =
        serde_json::to_vec(cursor).map_err(|e| AppError::Validation(format!("Could not encode page cursor: {e}")))?;
    Ok(base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(bytes))
}

/// Reject structurally-invalid segments at the DB write boundary, before they can
/// corrupt the downstream split/stats/training-grade math that every later stage
/// branches on. Guards the fields these insert paths actually persist; verdict and
/// human_decision are validated at their own dedicated write paths.
pub(super) fn validate_segment(seg: &SpeechSegment) -> AppResult<()> {
    if seg.id.trim().is_empty() {
        return Err(AppError::Validation("Segment id must not be empty".into()));
    }
    // P1.1: reject a UNC/network audio_path at the shared DB write boundary (covers merge_dataset_json
    // and every other insert path). A renderer-planted `\\attacker\share\clip.wav` would otherwise flow
    // into the row and drive the SMB redirector (NTLM forced-auth leak) the moment any downstream
    // consumer (validate_dataset, compute_acoustic_scores, decode) touches it. Syntactic, zero I/O; an
    // empty audio_path is allowed (not a UNC path). Mirrors the export-side guard shipped in #131.
    crate::validation::input::reject_unc_path(&seg.audio_path).map_err(AppError::Validation)?;
    if seg.duration_ms < 0 {
        return Err(AppError::Validation(format!(
            "Segment '{}' has a negative duration_ms ({})",
            seg.id, seg.duration_ms
        )));
    }
    if let Some(alignment) = seg.alignment_json.as_deref() {
        crate::validation::input::validate_alignment_json(alignment).map_err(AppError::Validation)?;
    }
    if let Some(split) = seg.split.as_deref() {
        if !VALID_SPLITS.contains(&split) {
            return Err(AppError::Validation(format!(
                "Segment '{}' has invalid split '{split}' (expected one of {VALID_SPLITS:?})",
                seg.id
            )));
        }
    }
    Ok(())
}

use crate::normalizer::learning_text_key;

/// Suspect-first review ordering (external review 2026-08-06 #2).
///
/// `agreement_score` on an escalated row is the IRT model-AGREEMENT confidence, and agreement is not
/// trustworthiness. A clip escalated because its AUDIO is poor — `has_hard_distrust_veto`'s snr < 5 dB
/// or clipping > 0.1 — can carry 0.97 there because every recognizer confidently agreed on the same
/// garbage. Ordering by that value alone sent exactly the clips the gate refused to trust to the BACK
/// of a queue whose whole purpose is riskiest-first.
///
/// So acoustic quality is ranked BEFORE agreement rather than being collapsed into it. The signals stay
/// separate — this reads them separately instead of averaging them into a single number that means
/// neither thing. No new column: snr_db and clipping_ratio are already on the row, which is why the
/// data to do this properly was there all along.
///
/// Order: escalated first; within that, poor audio first; then genuine disagreement (low agreement);
/// then newest.
/// P1.2: BUILT from `quality::POOR_AUDIO_*` rather than repeating the numbers. This string used to
/// carry its own hand-typed `< 5.0` / `> 0.1`, so changing the jury's veto thresholds silently left the
/// review queue ordering on the old rule — the queue would stop leading with the clips the gate had
/// just started distrusting, and nothing would report it.
///
/// The COALESCE defaults are deliberately "fine" values (99.0 dB SNR, 0.0 clipping) so an UNMEASURED
/// row sorts as unremarkable rather than as poor audio, matching `quality::has_poor_audio` treating
/// `None` as not-poor. Absence of a measurement is not evidence of bad audio.
pub(super) static SUSPECT_FIRST_ORDER: std::sync::LazyLock<String> = std::sync::LazyLock::new(|| {
    format!(
        "escalated DESC, \
         (CASE WHEN COALESCE(snr_db, 99.0) < {snr} OR COALESCE(clipping_ratio, 0.0) > {clip} THEN 0 ELSE 1 END) ASC, \
         COALESCE(agreement_score, 0.5) ASC, \
         datetime(created_at) DESC, id ASC",
        snr = crate::quality::POOR_AUDIO_SNR_DB,
        clip = crate::quality::POOR_AUDIO_CLIPPING_RATIO,
    )
});

pub(crate) fn rejected_transcript_for_learning(corrected: &str, candidates: &[Option<String>]) -> Option<String> {
    let corrected_key = learning_text_key(corrected);
    candidates.iter().filter_map(|candidate| candidate.as_deref()).find_map(|candidate| {
        let trimmed = candidate.trim();
        if trimmed.is_empty() || learning_text_key(trimmed) == corrected_key {
            None
        } else {
            Some(trimmed.to_string())
        }
    })
}
